import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Terms for using leadsheet.me, including eligibility, uploads, credits, and limitations.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <main
      className="standalone-page"
      style={{
        maxWidth: 760,
        margin: "0 auto",
        padding: "3rem 1.5rem 4rem",
        lineHeight: 1.6,
      }}
    >
      <Link
        href="/"
        style={{
          display: "inline-block",
          marginBottom: "1.5rem",
          color: "inherit",
          textDecoration: "none",
        }}
      >
        &larr; Go back
      </Link>
      <h1>Terms of Use for leadsheet.me</h1>
      <p>
        These terms describe how the service works, what you can upload, and the
        limits of responsibility for generated outputs.
      </p>
      <p>
        <strong>Effective date:</strong> 2026-02-12
        <br />
        <strong>Last updated:</strong> 2026-02-12
      </p>
      <p>
        These Terms of Use (“<strong>Terms</strong>”) govern your access to and
        use of <strong>leadsheet.me</strong> (the “<strong>Service</strong>”). By
        accessing or using the Service, you agree to these Terms. If you do not
        agree, do not use the Service.
      </p>

      <h2>1. Who we are</h2>
      <p>
        The Service is operated by <strong>Daniel Berger</strong>, a private
        individual, based in <strong>Austria</strong> (“<strong>Operator</strong>
        ”, “<strong>we</strong>”, “<strong>us</strong>”, “
        <strong>our</strong>”).
      </p>

      <h2>2. What the Service does</h2>
      <p>
        leadsheet.me lets you upload audio files of
        songs that you own or have rights to use. The Service uses AI-assisted
        analysis to generate <strong>draft</strong> lead sheets, including{" "}
        <strong>chords</strong> and <strong>song segments</strong>, and provides
        results as <strong>PDF</strong> and <strong>MusicXML</strong>.
      </p>
      <p>
        <strong>Important:</strong> The Service produces a{" "}
        <strong>best-effort draft</strong>. It is not guaranteed to be accurate,
        complete, or suitable for professional publication, performance, or any
        specific purpose.
      </p>

      <h2>3. Eligibility and account access</h2>
      <ul>
        <li>
          You must be able to form a legally binding contract to use the
          Service.
        </li>
        <li>
          You access the Service via <strong>Google Sign-In</strong>. You are
          responsible for maintaining the confidentiality and security of your
          Google account and for all activities that occur under your access.
        </li>
        <li>
          You agree to provide accurate information and to not impersonate
          others.
        </li>
      </ul>

      <h2>4. Your content and permissions</h2>
      <h3>4.1 Your uploads</h3>
      <p>
        You may upload music/audio files (“<strong>Uploads</strong>”). You
        represent and warrant that:
      </p>
      <ul>
        <li>
          you own the Uploads or have all necessary rights, permissions, and
          licenses to upload and process them through the Service; and
        </li>
        <li>
          your Uploads do not violate any laws or third-party rights (including
          copyright, neighboring rights, performer rights, privacy, or
          contractual restrictions).
        </li>
      </ul>

      <h3>4.2 License to operate the Service</h3>
      <p>
        You grant the Operator a limited, non-exclusive, worldwide license to
        host, process, analyze, and transform your Uploads{" "}
        <strong>solely to provide and improve the Service</strong> (including
        generating the requested outputs).
      </p>

      <h3>4.3 Responsibility for file quality and results</h3>
      <p>
        You are responsible for uploading reasonable-quality files and using
        the Service appropriately. While we may apply validation,{" "}
        <strong>validation cannot catch all issues</strong>. If you upload
        unsuitable files (e.g., wrong format, corrupted audio, noisy recordings,
        non-musical content), you may receive poor results. You accept that{" "}
        <strong>output quality depends heavily on input quality</strong>.
      </p>

      <h2>5. AI outputs and limitations</h2>
      <ul>
        <li>
          Outputs are generated by automated systems and may contain errors
          (wrong chords, wrong structure/segments, missing notes, wrong key,
          etc.).
        </li>
        <li>
          The Service is intended for <strong>personal use</strong> and as a{" "}
          <strong>draft</strong> to help you work faster, not as a guarantee of
          correctness.
        </li>
        <li>
          You are responsible for reviewing and verifying outputs before
          relying on them.
        </li>
      </ul>

      <h2>6. Credits, free generation, and payments</h2>
      <h3>6.1 Free generation</h3>
      <p>
        Your <strong>first generation</strong> is free (one free analysis run).
        We may change or discontinue free offers at any time.
      </p>

      <h3>6.2 Credit system</h3>
      <p>After the free generation, analyses require credits:</p>
      <ul>
        <li>
          You can purchase packs of <strong>5 credits</strong> or{" "}
          <strong>10 credits</strong>.
        </li>
        <li>
          <strong>One (1) credit</strong> equals <strong>one analysis run</strong>.
        </li>
        <li>
          Each analysis run can include <strong>up to five (5) songs</strong>.
        </li>
        <li>
          If you analyze fewer than 5 songs in a run (including only 1 song), it
          still costs <strong>1 credit</strong>.
        </li>
      </ul>

      <h3>6.3 Checkout and payment processor</h3>
      <p>
        Payments are processed through <strong>Stripe</strong>. By purchasing
        credits, you also agree to Stripe’s applicable terms and policies. We do
        not store your full payment card details; Stripe handles payment
        processing.
      </p>

      <h3>6.4 Pricing, taxes, and changes</h3>
      <p>
        Prices are shown in the checkout flow. Taxes may apply depending on
        your location and Stripe settings. We may change prices and credit pack
        offerings at any time; changes do not affect credits already purchased
        unless required by law or as otherwise stated.
      </p>

      <h3>6.5 No guarantee of success; consumption of credits</h3>
      <p>An analysis run may consume credits even if:</p>
      <ul>
        <li>your Upload is low quality,</li>
        <li>the output is incomplete,</li>
        <li>the result is not what you expected, or</li>
        <li>there is an error outside of our reasonable control.</li>
      </ul>
      <p>
        However, if there is a clear technical failure on our side resulting in{" "}
        <strong>no usable output</strong>, we may, at our discretion, restore
        the credit for that run.
      </p>

      <h3>6.6 Refunds</h3>
      <p>
        Because credits are a digital service, purchases may be{" "}
        <strong>non-refundable</strong> except where required by law. If you
        believe you were charged incorrectly, contact us with details of the
        issue.
      </p>

      <h2>7. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>upload content you do not have rights to use;</li>
        <li>use the Service to infringe copyright or other rights;</li>
        <li>attempt to reverse engineer, scrape, disrupt, or overload the Service;</li>
        <li>introduce malware or attempt unauthorized access;</li>
        <li>use the Service unlawfully or to violate others’ rights.</li>
      </ul>
      <p>
        We may suspend or terminate access if we reasonably believe you have
        violated these Terms.
      </p>

      <h2>8. Intellectual property</h2>
      <h3>8.1 Our IP</h3>
      <p>
        The Service, including its software, design, branding, and all related
        materials, is owned by the Operator and/or licensors and is protected by
        intellectual property laws. You receive a limited, non-exclusive,
        non-transferable license to use the Service for personal purposes in
        accordance with these Terms.
      </p>

      <h3>8.2 Your IP</h3>
      <p>
        As between you and us, you retain ownership of your Uploads. These Terms
        do not transfer ownership of your Uploads to us.
      </p>

      <h3>8.3 Outputs</h3>
      <p>
        Outputs (PDF/MusicXML) are generated based on your Uploads. To the
        extent permitted by law:
      </p>
      <ul>
        <li>you may use outputs for <strong>your personal use</strong>; and</li>
        <li>
          you are responsible for ensuring your use of the outputs does not
          infringe third-party rights (for example, if the Upload is a
          copyrighted recording or composition you do not own).
        </li>
      </ul>

      <h2>9. Service availability and changes</h2>
      <p>
        We may modify, suspend, or discontinue the Service (or any part of it)
        at any time. We do not guarantee uninterrupted availability.
        Maintenance, updates, outages, and changes in third-party services
        (e.g., Google Sign-In, Stripe, AI providers) may affect availability.
      </p>

      <h2>10. Disclaimers</h2>
      <p>To the maximum extent permitted by law:</p>
      <ul>
        <li>
          The Service is provided <strong>“as is”</strong> and{" "}
          <strong>“as available”</strong>.
        </li>
        <li>
          We make no warranties of any kind, express or implied, including
          merchantability, fitness for a particular purpose, non-infringement,
          or that outputs will be accurate, complete, or error-free.
        </li>
        <li>
          We do not warrant that the Service will be uninterrupted, secure, or
          free of bugs.
        </li>
      </ul>

      <h2>11. Limitation of liability</h2>
      <p>To the maximum extent permitted by law:</p>
      <ul>
        <li>
          The Operator will not be liable for indirect, incidental, special,
          consequential, or punitive damages, or for loss of profits, data,
          goodwill, or business opportunities, arising out of or related to your
          use of the Service.
        </li>
        <li>
          The Operator’s total liability for any claim arising out of or
          relating to the Service will not exceed the amount you paid to the
          Operator for credits in the <strong>three (3) months</strong> prior to
          the event giving rise to the claim (or <strong>EUR 0</strong> if you
          paid nothing).
        </li>
      </ul>
      <p>
        Nothing in these Terms limits liability that cannot be excluded under
        applicable law (for example, liability for intent or gross negligence
        where such limitation is prohibited).
      </p>

      <h2>12. Indemnity</h2>
      <p>
        You agree to indemnify and hold harmless the Operator from and against
        claims, damages, losses, and expenses (including reasonable legal fees)
        arising from:
      </p>
      <ul>
        <li>your Uploads,</li>
        <li>your misuse of the Service,</li>
        <li>your violation of these Terms, or</li>
        <li>your violation of any law or third-party right.</li>
      </ul>

      <h2>13. Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or terminate
        your access if you violate these Terms or if we reasonably believe
        continued access could create risk (legal, security, operational) for
        the Service or others.
      </p>
      <p>
        Upon termination, your right to use the Service ends. Credits may be
        forfeited upon termination for cause, to the extent permitted by law.
      </p>

      <h2>14. Consumer rights (EU/Austria)</h2>
      <p>
        If you are a consumer in the EU/Austria, you may have mandatory rights
        under applicable consumer laws. Nothing in these Terms affects rights
        that cannot be waived.
      </p>
      <p>
        <strong>Digital services note:</strong> In some cases, EU consumer law
        may provide rules regarding digital content/services, conformity, and
        remedies. Where such rules apply, they will prevail over conflicting
        parts of these Terms.
      </p>

      <h2>15. Governing law and jurisdiction</h2>
      <p>
        These Terms are governed by the laws of <strong>Austria</strong>,
        excluding conflict-of-law rules.
        <br />
        If you are a consumer in the EU, you may also benefit from mandatory
        protections of the laws of your country of residence.
      </p>
      <p>
        Any disputes that are not subject to mandatory consumer jurisdiction
        rules will be subject to the courts competent for the Operator’s place
        of residence in Austria.
      </p>

      <h2>16. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. The “Last updated” date
        will reflect changes. By continuing to use the Service after changes
        become effective, you agree to the updated Terms.
      </p>

      <h2>17. Contact</h2>
      <p>For questions, support, or legal notices, contact the Operator:</p>
      <p>
        <strong>Daniel Berger</strong>
        <br />
        <strong>leadsheet.me</strong>
        <br />
        Austria
        <br />
        <strong>Contact:</strong> (office@leadsheet-app.com)
      </p>

      <hr />

      <h2>Plain-language summary (not legally binding)</h2>
      <ul>
        <li>
          leadsheet.me generates <strong>draft</strong> lead sheets (PDF/MusicXML)
          from your uploaded songs using AI.
        </li>
        <li>
          First analysis is free; after that you buy credits (5 or 10).
        </li>
        <li>
          <strong>1 credit = 1 analysis run</strong> (up to 5 songs per run).
          Even 1 song costs 1 credit.
        </li>
        <li>
          Upload only files you have rights to, and don’t expect perfection—input
          quality affects output quality.
        </li>
        <li>
          We’re not liable for mistakes in the generated music or for how you
          use it.
        </li>
      </ul>
    </main>
  );
}
